name: Check code style

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  codestyle:
    runs-on: ubuntu-latest
    name: Codestyle

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Bootstrap workspace
        uses: ./.github/actions/bootstrap-workspace
        with:
          node-auth-token: ${{ secrets.GHA_PAT }}

      - name: Run eslint
        run: pnpm run eslint:check

      - name: Run prettier
        run: pnpm run prettier:check
