name: Collect and publish contract deployments using Github Pages

on:
  push:
    branches:
      - main
    paths:
      - "contracts/**/.openzeppelin/**"
      - "scripts/collect-deployments/**"
      - ".github/workflows/deployments.yml"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  collect-deployments:
    runs-on: ubuntu-latest
    name: Collect deployment info
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Bootstrap workspace
        uses: ./.github/actions/bootstrap-workspace
        with:
          node-auth-token: ${{ secrets.GHA_PAT }}

      - name: Collect deployments
        run: pnpm run collect-deployments deployments-output
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deployments-output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: collect-deployments
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
