name: Collect contract signatures and make PR to update them in Stratus repository

on:
  push:
    branches:
      - main

jobs:
  collect-signatures:
    runs-on: ubuntu-latest
    name: Collect signatures
    env:
      MISE_BACKENDS_SOLIDITY: asdf:diegodorado/asdf-solidity
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Bootstrap workspace
        uses: ./.github/actions/bootstrap-workspace
        with:
          node-auth-token: ${{ secrets.GHA_PAT }}

      - name: Install mise
        uses: jdx/mise-action@v3
        with:
          install_args: solidity # uses root .tool-versions and default version from it

      - name: Generate signatures
        run: ./scripts/generate-signatures.bash
        shell: bash

      - name: Save artifact
        uses: actions/upload-artifact@v6
        with:
          name: contract-signatures
          path: signatures
          overwrite: true
  make-pr:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Update signatures in Stratus repository
    needs: collect-signatures
    permissions:
      contents: write
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.DEV_EX_APP_ID }}
          private-key: ${{ secrets.DEV_EX_APP_PRIVATE_KEY }}
          repositories: stratus
          owner: cloudwalk

      - name: Checkout Stratus repository
        uses: actions/checkout@v6
        with:
          repository: cloudwalk/stratus
          path: stratus
          token: ${{ steps.app-token.outputs.token }}

      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: contract-signatures
          path: stratus/static/contracts-signatures

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          path: stratus
          token: ${{ steps.app-token.outputs.token }}
          branch: brlc/update-contract-signatures
          delete-branch: true
          sign-commits: true
          title: "auto: update contract signatures"
          body: |
            This PR updates the contract signatures.

            The updated signature files are located in `static/contracts-signatures`.

            This is an automated PR created by changes in smart contracts in the `brlc-monorepo` repository.
          base: main
          labels: |
            automated
          draft: false
          maintainer-can-modify: false
          commit-message: "auto: update contract signatures"
